### ISSUE TITLE
Problems with nested repeaters and custom field

### ISSUE THREAD

**Issue by SamuelNCarvalho** [siteorigin/so-widgets-bundle#775] opened 2018-11-08 18:10 UTC
The issue #768 has been fixed? I'm having the same problem with this version of so-widgets-bundle.
I have the following widget: https://codeshare.io/2WjERE
And the following field: https://codeshare.io/aYrEXQ

When saving the post, it is creating a new copy of the added item. And the field I created is not persisting the data, because after adding the data-name it is removing the name of the html.

Could you help me, I'm having big problems because of this bug.

**Comment by AlexGStapleton** [comment] 2018-11-08 22:09
Closing due to duplicate of #768

**Closed by AlexGStapleton** 2018-11-08 22:09 UTC
Labels: duplicate
