### ISSUE TITLE
Dropdown in post selector not working in Firefox

### ISSUE THREAD

**Issue by ernilambar** [siteorigin/so-widgets-bundle#252] opened 2016-06-30 06:00 UTC
Steps to reproduce:
- Activate TwentySixteen theme.
- Activate Siteorigin Panel and Widget Bundle.
- In page add `Post Loop` widget.
- Click `Build Posts Query`
- Click `Order by`. Dropdown should open but it does not.

System:
WP: 4.6-beta1-37926
Browser: Firefox 47.0
Page Builder by SiteOrigin: 2.4.9
SiteOrigin Widgets Bundle: 1.6.1

**Comment by AlexGStapleton** [comment] 2016-06-30 06:56
I'm not able to replicate this issue. To clarify, have you run a full plugin conflict test (see below)? And if so, are you able to replicate this issue in the current version of WordPress?

Here's the plugin conflict test:
Can you try disabling all non-SiteOrigin plugins and see if this fixes the issue? You'll need to [clear all your caches](https://codex.wordpress.org/I_Make_Changes_and_Nothing_Happens) after disabling your plugins.

If it does fix the issue, then try re-enabling your plugins one by one until the issue comes back. This procedure will help diagnose which plugin is causing the issue.

If you aren't using a SiteOrigin theme, then you can also try temporarily switching to one of the default WordPress themes to see if the issue is theme related.

**Comment by ernilambar** [comment] 2016-06-30 07:38
Thanks for the reply. Yes, I have already done plugin conflict test. Thats why I chose Twenty Sixteen theme. And all non-siteorigin plugins disabled. You can try in this my testing site.

Site: http://altruism.thisistap.com/wp-admin/
U: tempadmin
P: temppassword@123

**Comment by ernilambar** [comment] 2016-06-30 07:55
I checked in Chrome and it is working fine. I get this only in Firefox. Actually this issue was reported in our one the theme which uses Siteorigin Builder. 
http://themepalace.com/topic/special-dish-widget-orderby-selection-issue/
I tested in my theme but I felt this is plugin issue. I tested with TwentySixteen and same problem. Now I am not sure how should I reply to user. :unamused:

**Comment by wensolutions** [comment] 2016-06-30 10:42
@AlexGStapleton , I am too facing a similar issue [http://prntscr.com/bmzc38](url) .

Not being able to select the options from the drop-down **Order by**

Specifications as follows : 

FireFox - 47.0.1 [latest]
WordPress - 4.5.3 [latest]
Page Builder by SiteOrigin: 2.4.9
SiteOrigin Widgets Bundle: 1.6.1


All other plugins disabled to avoid conflicts !

Tested on default themes twentyfifteen and twentysixteen still not working. 

Chrome : OK 

This is going troublesome in Firefox as my theme is dependent to this plugin.

Is there any quick fix for this ?

**Comment by AlexGStapleton** [comment] 2016-06-30 11:41
I was able to replicate this with your information. Gonna forward this on. Issue only happens in FireFox 47 as far as I can tell.

**Comment by wensolutions** [comment] 2016-06-30 11:57
:+1:  Thank you.. waiting and hoping to get this fixed soon

**Comment by gregpriday** [comment] 2016-06-30 16:20
Thanks for the very clear report @ernilambar. We'll be looking into this shortly.

**Comment by AlexGStapleton** [comment] 2016-07-27 16:25
@gregpriday The fix for this was released in 1.6.2, right?

**Closed** 2017-02-03 14:05 UTC
