### ISSUE TITLE
update_meta_chase() fetches wrong post ID

### ISSUE THREAD

**Issue by arnaudbroes** [siteorigin/so-widgets-bundle#779] opened 2018-11-13 18:34 UTC
For more details, please refer to https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/2045. 

> I've identified this as a bug with the SiteOrigin Widgets Bundle plugin. It runs a query using update_meta_chase() against the wp_postmeta table against the wrong post ID. This causes the wrong post ID to be stored.
> 
> I verified this by deactivating all other plugins except Gutenberg, Page Builder by SiteOrigin and SiteOrigin Widgets Bundle and created a new post. Once the post was saved as a Draft, I clicked on View Post in the Admin Bar and it took me to the wrong post. I also verified this with the Query Monitor plugin. ~ Steve Mortiboy

**Comment by AlexGStapleton** [comment] 2018-11-14 03:45
I suspect this issue was introduced after a recent fix to avoid a Gutenberg bug. I'm not too familiar with the changes made to avoid that issue but I've had a look around and I can't seem to find any usage of `update_meta_chase`. Are you able to provide any additional information?

**Comment by AlexGStapleton** [comment] 2018-11-14 03:54
@braamgenis Can you please take a look at this? The linked thread specifically highlights the Post Carousel widget.

**Comment by braamgenis** [comment] 2018-11-14 18:50
I've never heard of `update_meta_chase` before and I'm quite sure it's not a thing.

This sounds a bit like the issue we had with secondary queries affecting the global `$post` variable, but this was fixed in a recent release.  If you're using the most recent version and this is still happening with only the Widgets Bundle installed, we'd need some more info, like steps to reproduce etc.

**Comment by arnaudbroes** [comment] 2018-11-15 20:01
I'm not personally using it; this was on a client site.

You should be able to reproduce the issue by installing All in One SEO Pack, combined with SiteOrigin Widgets Bundle and by activating the Post Carousel widget. When you subsequently create a new Post/Page, the SEO title and SEO meta description in our plugin's meta box will be filled in with some random data, but they should be blank. It's fetching this data from other different posts because the wrong post ID is stored.

**Comment by braamgenis** [comment] 2019-02-11 18:22
Could not reproduce. Can reopen if this comes up again.

**Closed by braamgenis** 2019-02-11 18:22 UTC
Labels: plugin/theme conflict, priority-3
