### ISSUE TITLE
Layer Slider: Disable height setting or put in option to remove height on mobile devices

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#307] opened 2016-08-24 05:33 UTC
The layer slider has a serious problem in that if you set a height and then add multiple columns or a few rows to exceed this height limit, it won't display correctly on mobile devices as the other rows / columns will not be visible

![](https://i.imgur.com/42oFAsp.gif)

[Here's a reference layout](https://u.teknik.io/m35Iv.json), the height is set very low to make it easier to see this issue without having to scroll for every.

**Comment by Misplon** [comment] 2018-05-10 08:13
**Alex notes:**
Might be a good idea to add an optional setting "automatically calculate height on mobile" rather than forcefully preventing height from being applied.

@AlexGStapleton Perhaps chat to Braam about the above setting idea.

**Comment by braamgenis** [comment] 2018-06-25 15:15
@AlexGStapleton I started looking into this to review #708 and get it merged. In my tests the issue seems to be larger than just on mobile. I see the columns overflowing the height in some themes, but not in others, on desktop and without having set a height at all.

Steps to reproduce: 

1) Create a new page and add a Layout Slider
2) In the Layout Slider, create a new row with 3 columns and add 3 Editor widgets with a fair amount of text.
3) Publish and View Page.
4) Depending on which theme is being used the content overflows the height, presumably of the widget.

Themes tested: Vantage, Corp, North, Origami, Unwind, Twenty Fifteen, Twenty Sixteen, Twenty Seventeen.

Works in: Vantage, Corp, North, Origami, Twenty Seventeen

Overflows in: Unwind, Twenty Fifteen, Twenty Sixteen.

Let me know if you'd like me to look into it further.

A side note: I think we'd need to redo that PR in a new branch to avoid having all those merge commits in our history. We don't have the cleanest commit history, but don't need to make it make it worse if we can avoid it. :P

**Comment by AlexGStapleton** [comment] 2018-06-26 05:15
All of those merge commits? Oh whoops! Just corrected it. 

Okay, so I can't seem to replicate the overflow without setting a hard height in any of the stated themes. Maybe I'm looking for something different to what is actually happening. By overflow, you mean the same overflow present in the image in the issue, right? Can you send me an export of your testing layout?

**Comment by braamgenis** [comment] 2018-06-26 08:31
Here's the exported layout created as I stated above and a screengrab showing the issue: [wb-layout-slider.zip](https://github.com/siteorigin/so-widgets-bundle/files/2136234/wb-layout-slider.zip)

**Comment by AlexGStapleton** [comment] 2018-06-26 13:11
Huh. Quick question - does that export work for you? The layout builder data isn't being imported for me.

Regardless, that appears to be a general issue with the automatic slide height functionality rather than an issue directly related to this one. This one is purely an issue with the height the user set on mobile. Does that make sense?

**Comment by braamgenis** [comment] 2018-06-28 09:14
Ok, so I fixed the height issue I was seeing. It may be related to some widget initialization changes I made. It seems we're not parsing the nested PB data when importing layouts. I've logged an issue for that. After that nice little detour 😩, will carry on with review.

**Closed** 2018-10-12 21:20 UTC
Labels: bug, priority-1
