### ISSUE TITLE
When Maps widget is added to a sidebar it doesn't work

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#245] opened 2016-06-23 04:09 UTC
[This line](https://github.com/siteorigin/so-widgets-bundle/blame/develop/widgets/google-map/js/js-map.js#L200) is causing an issue for SiteOrigin Google Maps widgets being added to sidebars.

![](https://i.imgur.com/0oakuJ0.png)

To replicate simply add this widget to a sidebar (WP Admin > Appearance > Widgets). You do not need to make any changes to the widget as the default settings will cause the issue.

**Comment by gregpriday** [comment] 2016-06-23 07:30
I'm not sure if my issue is related, but this is what I'm getting when I add a Maps widget to the sidebar.

![screen shot 2016-06-23 at 8 47 39 am](https://cloud.githubusercontent.com/assets/1126859/16295124/2b127926-3925-11e6-9972-37d99e604454.png)

Everything works as expected on a standard Page Builder page.

**Comment by braamgenis** [comment] 2016-06-23 09:00
@AlexGStapleton I can't seem to reproduce the issue and after some further testing, @gregpriday is no longer seeing any errors either. On the small chance you haven't already, could you try clearing cache and checking again? Thanks!

**Comment by AlexGStapleton** [comment] 2016-06-23 10:37
Sorry for the delay. I've run a few more tests and if you're viewing a Page Builder powered page it will work as expected. Please view a random non-page builder page.

**Comment by braamgenis** [comment] 2016-06-23 10:46
Just tried viewing a normal post and still not seeing the issue. :confused: 
Which theme are you using? I've checked using North, Vantage and Twenty Sixteen.

**Comment by gregpriday** [comment] 2016-06-23 10:50
Sneaky issue. For me the issue is back. Getting the `MissingKeyMapError`. 

Seems like the API key might be required. Probably find it's rolling out to different data centers which is why the issue is intermitted for me.

https://wordpress.org/support/topic/google-maps-api-error-missingkeymaperror-1?replies=2

@alex - are you seeing the original `apiKey of undefined` error, or the `MissingKeyMapError` error?

**Comment by gregpriday** [comment] 2016-06-23 10:51
Yup. From the blog post yesterday - http://googlegeodevelopers.blogspot.co.za/2016/06/building-for-scale-updates-to-google.html

> We no longer support keyless access (any request that doesn't include an API key). Future product updates are only available for requests made with an API key. API keys allow us to contact developers when required and help us identify misbehaving implementations.

**Comment by AlexGStapleton** [comment] 2016-06-23 11:03
@braamgenis I was using Vantage. :confused: 

Awkwardly I can't replicate this any longer. Very likely the issue is related to the change @gregpriday mentioned. I suspect this issue will fix itself once the changes get pushed out fully. Admitally it will break existing Google Maps. I think it might be a good idea to enforce an API in the next version. Maybe add a setting field in the Page Builder settings? That way if the user has a few widgets present they won't need to repeat it for every field.

**Comment by braamgenis** [comment] 2016-06-23 11:09
Same day we release an update. Amazing timing. :stuck_out_tongue_closed_eyes: 

@AlexGStapleton Yeah, looks like we have no choice but to make it a required field now. We've discussed having a single place to enter an API key, so will think about how to introduce some global settings page.

I'm still slightly concerned about the issue you were seeing though as it doesn't seem to have anything to do with API keys being required. It looks like the map configuration options might be completely missing, but we'll see if it shows up again.

**Comment by AlexGStapleton** [comment] 2016-06-23 14:19
Hm. This issue isn't very consistent. I'm going to send you a reference site over Slack but basically, it looks like js-map.min.js is being loaded sometimes when there is no Google Maps widget present - hence the lack of settings.

**Comment by AlexGStapleton** [comment] 2016-06-23 14:52
[Slack chat reference link](https://siteorigin.slack.com/archives/plugins/p1466691585000041)

**Comment by AlexGStapleton** [comment] 2016-07-01 03:26
I'm positive this was fixed in the last update as I haven't seen a single report since. This issue just wasn't referenced. Is that the case @braamgenis? (just asking if it can be closed or not)

**Comment by braamgenis** [comment] 2016-07-01 10:03
Yeah, we shouldn't be seeing the JS error anymore from this commit: 5c6f1f6dfade550f1ef5d5d3eb4f4c45580006ea , but things still won't work without API key.

Closing.

**Closed by braamgenis** 2016-07-01 10:03 UTC
Labels: bug, priority-1
