### ISSUE TITLE
<br> added inside button plugin when using WP-Members

### ISSUE THREAD

**Issue by xNok** [siteorigin/so-widgets-bundle#261] opened 2016-07-08 09:06 UTC
When I use both siteOrigin button widget and WP-Members I've got this issue -> the button height increase. 

![image](https://cloud.githubusercontent.com/assets/9772542/16681901/d860375a-453a-11e6-931b-edc92b27b580.png)

On this demo wordpress only 2 plugin are enabled. I see that `<br>` tags have been added during the template rendering.

I have use the code of the widget to investigate this issue. When I put all inline element on the same line no issues anymore. I know that the code is note human readable anymore. So I'm wondering if you have any clue on this issue

**Comment by AlexGStapleton** [comment] 2016-07-27 16:21
Sorry! I somehow missed this! 

Would it be possible for you to send me an export for this widget? To do this open up the page with the widget and click layout. Then click import / export and then click download. Please upload the export to a 3rd party file hosting site such as <a href="https://upload.teknik.io/">teknik.io</a>.

**Comment by xNok** [comment] 2016-07-28 00:13
hi,

I use those dependencies :
* https://wordpress.org/plugins/wp-members/ - Version 3.1.3.1
* https://wordpress.org/plugins/so-widgets-bundle/ - Version 1.6.4 
* theme: Twenty Sixteen on my sandbox

The exported file as required : https://u.teknik.io/OjNxw.json

Button widget from my web browser : 
```html
<div class="so-panel widget widget_sow-button panel-first-child panel-last-child" id="panel-2-1-1-0" data-index="2">
<div class="so-widget-sow-button so-widget-sow-button-flat-4db25db0d37e">
<div class="ow-button-base ow-button-align-center">
<p>
<a class="ow-button-hover"><br>
		<span><br>
			<span class="sow-icon-fontawesome" data-sow-icon=""></span><br>
			LOGIN		</span><br>
	</a>
</p>
</div>
</div>
</div>
```

A very minimalist tpl that solve this issue, by putting all inline html tags in a single line.
```
<div class="thinxtra-button-base thinxtra-button-align-center">
    <a class="thinxtra-button-hover" onClick="<?php echo wp_kses_post($instance['js']) ?>"><?php echo siteorigin_widget_get_icon( $instance['icon'], $icon_styles ); ?></span><?php echo wp_kses_post($instance['text']) ?></span></a>
</div>
```

PS: you must be log out when displaying this page to be able to render the login form.

**Comment by AlexGStapleton** [comment] 2016-07-28 08:46
I'm not able to replicate this issue with the layout provided. The only major difference I can see is the usage of a Thinxtra button widget. Said widget I don't have. Does this issue resolve itself by removing that button widget (or alternatively disabling the plugin that has added that)?

**Comment by braamgenis** [comment] 2017-02-13 12:02
I can't reproduce either and can't do much without further input from @xNok . It's been more than 6 months so I'm going to close this and if we get further feedback, I'll reopen and look into it further.

**Closed by braamgenis** 2017-02-13 12:02 UTC
