### ISSUE TITLE
State Emitter not working inside sub-widget of "widget" field

### ISSUE THREAD

**Issue by MichaelPote** [siteorigin/so-widgets-bundle#502] opened 2017-07-03 12:55 UTC
I have two widgets, a 'sub-widget' that is getting pulled into my main widget via a "widget" field inside the main widget's settings form.

The sub-widget has a state emitter tied to a select field. the state emitter is using the `select` callback. When I open the sub-widget's settings page from within my main widget, the state emitter fails to fire the first time and doesn't show anything until I manually select something else on my select field.

**Comment by AlexGStapleton** [comment] 2019-02-11 00:01
Hi Michael,

I'm really sorry for the delay. Do you happen to have the widget for this still? If so, can you please provide me with a copy of your code so we can see this issue? We don't really have any widgets with this setup so that would help us. If you don't, that's completely fine.

**Comment by MichaelPote** [comment] 2019-02-11 20:32
Hi Alex,

No worries. I had a look back into my commit history and think these are the files I was working on at the time. 

I've just included the two widget classes (main and subwidget). They wont execute - they're missing a whole bunch of supporting files, but have a look at the widget fields defined in the widget constructor. Perhaps you can see how I set the two up and replicate the structure in your own testing.

Thanks!

[Code Send.zip](https://github.com/siteorigin/so-widgets-bundle/files/2852931/Code.Send.zip)

**Comment by gregpriday** [comment] 2019-02-13 06:47
Thanks @MichaelPote!

@AlexGStapleton can you test this when you get a chance? Given that state emitters are working better in general these days from unrelated fixes, perhaps this is working properly too now.

**Comment by AlexGStapleton** [comment] 2019-02-13 12:40
Unfortunately, this issue is still happening. 😞 
The easiest way to replicate this issue is to edit the Button widget and give one of the settings a state_emitter (and another a state_handler). Then add a SiteOrigin Hero widget to the page, add a new frame and then open the Button settings and you'll receive this JavaScirpt error message:

```
VM1243:formatted:1 Uncaught ReferenceError: val_1 is not defined
    at eval (eval at <anonymous> (admin.min.js?ver=1.15.0-rc.5:formatted:725), <anonymous>:1:1)
    at admin.min.js?ver=1.15.0-rc.5:formatted:725
    at Object._checker (admin.min.js?ver=1.15.0-rc.5:formatted:713)
    at Object.conditional (admin.min.js?ver=1.15.0-rc.5:formatted:724)
    at i (admin.min.js?ver=1.15.0-rc.5:formatted:228)
    at HTMLInputElement.m (admin.min.js?ver=1.15.0-rc.5:formatted:235)
    at HTMLInputElement.<anonymous> (admin.min.js?ver=1.15.0-rc.5:formatted:251)
    at Function.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.each (jquery.js?ver=1.12.4:2)
    at HTMLDivElement.<anonymous> (admin.min.js?ver=1.15.0-rc.5:formatted:249)
    at Function.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.each (jquery.js?ver=1.12.4:2)
    at HTMLDivElement.<anonymous> (admin.min.js?ver=1.15.0-rc.5:formatted:246)
    at Function.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.C.fn.sowSetupForm (admin.min.js?ver=1.15.0-rc.5:formatted:4)
    at HTMLDivElement.<anonymous> (admin.min.js?ver=1.15.0-rc.5:formatted:109)
    at Function.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.C.fn.sowSetupForm (admin.min.js?ver=1.15.0-rc.5:formatted:4)
    at HTMLDivElement.<anonymous> (admin.min.js?ver=1.15.0-rc.5:formatted:112)
    at Function.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.C.fn.sowSetupForm (admin.min.js?ver=1.15.0-rc.5:formatted:4)
    at HTMLDivElement.<anonymous> (admin.min.js?ver=1.15.0-rc.5:formatted:506)
    at Function.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.C.fn.sowSetupRepeaterItems (admin.min.js?ver=1.15.0-rc.5:formatted:392)
    at HTMLDivElement.<anonymous> (admin.min.js?ver=1.15.0-rc.5:formatted:117)
    at Function.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.C.fn.sowSetupForm (admin.min.js?ver=1.15.0-rc.5:formatted:4)
    at HTMLDivElement.<anonymous> (admin.min.js?ver=1.15.0-rc.5:formatted:506)
    at Function.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.C.fn.sowSetupRepeaterItems (admin.min.js?ver=1.15.0-rc.5:formatted:392)
    at HTMLDivElement.<anonymous> (admin.min.js?ver=1.15.0-rc.5:formatted:117)
    at Function.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.C.fn.sowSetupForm (admin.min.js?ver=1.15.0-rc.5:formatted:4)
    at eval (eval at <anonymous> (jquery.js?ver=1.12.4:2), <anonymous>:7:68)
    at eval (eval at <anonymous> (jquery.js?ver=1.12.4:2), <anonymous>:15:7)
    at eval (<anonymous>)
    at jquery.js?ver=1.12.4:2
    at Function.globalEval (jquery.js?ver=1.12.4:2)
    at Ha (jquery.js?ver=1.12.4:3)
    at a.fn.init.append (jquery.js?ver=1.12.4:3)
    at a.fn.init.<anonymous> (jquery.js?ver=1.12.4:3)
    at Y (jquery.js?ver=1.12.4:3)
    at a.fn.init.html (jquery.js?ver=1.12.4:3)
    at n.<anonymous> (siteorigin-panels-2101.min.js?ver=2.10.1:1)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:2)
    at y (jquery.js?ver=1.12.4:4)
    at XMLHttpRequest.c (jquery.js?ver=1.12.4:4)
```

You'll be unable to open the sections when this error occurs.

**Comment by gregpriday** [comment] 2019-02-13 13:57
I'll take a look. Can you edit `so-widgets-bundle.php`, near the top you should see `define('SOW_BUNDLE_JS_SUFFIX', '.min');`, can you change that to `define('SOW_BUNDLE_JS_SUFFIX', '');`, then get the error message again? The errors are much easier to follow in unminified files.

**Comment by AlexGStapleton** [comment] 2019-02-13 14:01
```
Uncaught ReferenceError: val_1 is not defined
    at eval (eval at <anonymous> (admin.js:1359), <anonymous>:1:1)
    at admin.js:1359
    at Object._checker (admin.js:1318)
    at Object.conditional (admin.js:1358)
    at handleStateEmitter (admin.js:426)
    at HTMLInputElement.stateEmitterChangeHandler (admin.js:438)
    at HTMLInputElement.<anonymous> (admin.js:476)
    at Function.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.each (jquery.js?ver=1.12.4:2)
    at HTMLDivElement.<anonymous> (admin.js:467)
    at Function.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.each (jquery.js?ver=1.12.4:2)
    at HTMLDivElement.<anonymous> (admin.js:459)
    at Function.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.$.fn.sowSetupForm (admin.js:9)
    at HTMLDivElement.<anonymous> (admin.js:218)
    at Function.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.$.fn.sowSetupForm (admin.js:9)
    at HTMLDivElement.<anonymous> (admin.js:224)
    at Function.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.$.fn.sowSetupForm (admin.js:9)
    at HTMLDivElement.<anonymous> (admin.js:887)
    at Function.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.$.fn.sowSetupRepeaterItems (admin.js:712)
    at HTMLDivElement.<anonymous> (admin.js:237)
    at Function.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.$.fn.sowSetupForm (admin.js:9)
    at HTMLDivElement.<anonymous> (admin.js:887)
    at Function.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.$.fn.sowSetupRepeaterItems (admin.js:712)
    at HTMLDivElement.<anonymous> (admin.js:237)
    at Function.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.$.fn.sowSetupForm (admin.js:9)
    at eval (eval at <anonymous> (jquery.js?ver=1.12.4:2), <anonymous>:7:68)
    at eval (eval at <anonymous> (jquery.js?ver=1.12.4:2), <anonymous>:15:7)
    at eval (<anonymous>)
    at jquery.js?ver=1.12.4:2
    at Function.globalEval (jquery.js?ver=1.12.4:2)
    at Ha (jquery.js?ver=1.12.4:3)
    at a.fn.init.append (jquery.js?ver=1.12.4:3)
    at a.fn.init.<anonymous> (jquery.js?ver=1.12.4:3)
    at Y (jquery.js?ver=1.12.4:3)
    at a.fn.init.html (jquery.js?ver=1.12.4:3)
    at n.<anonymous> (siteorigin-panels-2101.min.js:1)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:2)
    at y (jquery.js?ver=1.12.4:4)
    at XMLHttpRequest.c (jquery.js?ver=1.12.4:4)
```

**Comment by gregpriday** [comment] 2019-02-13 15:04
I couldn't see anything obvious. Going to assign to @braamgenis. I originally wrote state emitters, but that was a long time ago. Braam has fixed issues with them more recently, so hopefully he is clearer on how they work than me.

**Comment by braamgenis** [comment] 2019-02-14 19:31
@AlexGStapleton I couldn't reproduce this. I edited the Button widget settings (see below) then added a button in a frame to a hero widget and didn't get any errors. I also created a custom widget form containing two `widget` fields, each containing a Maps widget and all the state emitters seemed to work as expected. Could you provide a code example that creates the issue?
```
'icon' => array(
	'type' => 'media',
	'label' => __('Image icon', 'so-widgets-bundle'),
	'description' => __('Replaces the icon with your own image icon.', 'so-widgets-bundle'),
	'state_handler' => array(
		'icon_placement[none]' => array( 'hide' ),
		'_else[icon_placement]' => array( 'show),
	),
),
'icon_placement' => array(
	'type' => 'select',
	'label' => __( 'Icon Placement', 'so-widgets-bundle' ),
	'default' => 'left',
	'options' => array(
		'none'    => __( 'None', 'so-widgets-bundle' ),
		'top'    => __( 'Top', 'so-widgets-bundle' ),
		'right'  => __( 'Right', 'so-widgets-bundle' ),
		'bottom' => __( 'Bottom', 'so-widgets-bundle' ),
		'left'   => __( 'Left', 'so-widgets-bundle' ),
	),
	'state_emitter' => array(
		'callback' => 'select',
		'args' => array( 'icon_placement' )
	),
),
```

**Comment by AlexGStapleton** [comment] 2019-02-14 20:26
That code works for me. Hm. Oh... I copied the wrong `state_emitter`. The above error is actually related to the `conditional` callback.

Here's the modified code in the button widget:

```
'hover' => array(
	'type' => 'checkbox',
	'default' => true,
	'label' => __('Use hover effects', 'so-widgets-bundle'),
	'state_emitter' => array(
		'callback' => 'conditional',
		'args'     => array(
			'hover[yes]: val',
			'hover[no]: !val'
		),
	),
),

'font' => array(
	'type' => 'font',
	'label' => __( 'Font', 'so-widgets-bundle' ),
	'default' => 'default',
	'state_handler' => array(
		'hover[yes]' => array( 'show' ),
		'hover[no]' => array( 'hide' ),
	)
),

```

[Here's a copy of the edited button.php file](https://gist.githubusercontent.com/AlexGStapleton/589fff412c90a95ecbbfdf94500cce09/raw/fbb9ebfe23c95fa74c7ff6bf81d6e0894f6827dd/button.php).

**Closed** 2019-02-15 17:33 UTC
Labels: bug, priority-3
