### ISSUE TITLE
Editor: Prevent Editor from appearing under WP sidebar on low resolution computers

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#542] opened 2017-08-21 09:17 UTC
A user has reported on his MacBook Pro 13 Retina (2560×1600, scaled to 1280 x 800), that the SiteOrigin Editor widget is appearing below the WP sidebar on the Widgets screen. We should account for this and prevent this from happening.

![](https://i.imgur.com/J6zLiQi.png)

**Comment by gregpriday** [comment] 2019-02-13 12:18
This is actually a duplicate of https://github.com/siteorigin/so-widgets-bundle/issues/574

You can see my [last comment](https://github.com/siteorigin/so-widgets-bundle/issues/574#issuecomment-462664570) for reasons why we can't/shouldn't fix this.

**Closed by gregpriday** 2019-02-13 12:18 UTC
Labels: bug, priority-3
