### ISSUE TITLE
Jetpack Photon: Incorrectly resizing images in SiteOrigin Editor widget

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#428] opened 2017-03-13 09:41 UTC
A number of users have recently reported sizing issues with images added to the SiteOrign Editor widget when Jetpack Photon is active. Photon is outputting full size locally hosted images. I seem to remember reading something about a recent responsive change for images but I can't seem to find reference to it - that likely could have caused this conflict.

**Comment by AlexGStapleton** [comment] 2017-03-22 15:58
[User posted about this here](https://siteorigin.com/thread/custom-image-size-is-not-working-in-editor-plugin/). [This comment](https://siteorigin.com/thread/custom-image-size-is-not-working-in-editor-plugin/#comment-118110) looks to be very important and may provide potential directions.

`Removing wp-image-220 from the HTML tag fixed the issue for that particular text widget, but I would need to remove it from every one of my posts or use a plugin to block it. I opted to deactivate the Photon Module instead.`

**Comment by jeherve** [comment] 2017-03-22 21:26
Hi @AlexGStapleton! I work on the Jetpack plugin and would love to find a solution to that conflict.

Here is some background about what's happening:

In the most recent Jetpack update ([4.7.1](https://github.com/Automattic/jetpack/releases/tag/4.7.1), we added the following changes: https://github.com/Automattic/jetpack/pull/6434

In short, before 4.7.1 Jetpack didn't touch text widgets at all; since 4.7.1, if Jetpack's [Photon module](http://jetpack.com/support/photon) is active on the site, we apply Photon to the content of the text widgets.

In practice, this means that we do the following:
1. We grab all image tags inside each text widget.
2. For each image tag, we grab `src`, `width` and `height`,  CSS classes defining a specific image size (e.g. `size-medium`), and WP attachment IDs (e.g. `wp-image-220`).
3. We use that information to rebuild an image tag where the image will be served by Photon, and resized to match the parameters given in the original image tag.

In most cases this works well. Here is an example, where the text widget includes an image tag that was first inserted into a post via the Add Media modal, and then copied and pasted into a text widget:

```html
<img src="http://mysite.com/wp-content/uploads/2017/03/test-photon-150x150.jpeg" alt="" width="150" height="150" class="aligncenter size-thumbnail wp-image-1242" />
```

This gets converted into:

```html
<img src="https://i2.wp.com/mysite.com/wp-content/uploads/2017/03/test-photon.jpeg?resize=150%2C150" alt="" class="aligncenter size-thumbnail wp-image-1242" width="150" height="150">
```

As you can see the `resize` parameters and the `width` and `height` parameters match the original image. All is well. No display issues.

Unfortunately, something seems to fail on some sites, including some that use SiteOrign Editor widgets. The user who contacted you [here](https://siteorigin.com/thread/custom-image-size-is-not-working-in-editor-plugin/) also reached out to us [in the forums](https://wordpress.org/support/topic/custom-image-size-not-working-since-jetpack-update-4-7-1/). Here is the HTML for their image tag:

```html
<img class="aligncenter wp-image-220" src="http://novelgobblers.com/wp-content/uploads/2015/11/NGicon.png" width="75" height="76" />
```

We can notice a few differences:
1. Although there are align and WP attachment ID classes, there is no size class. That's most likely because...
2. The `width` and `height` parameters are custom; they don't match any media size on their site (they use the default settings under Settings > Media, so thumbnails are set to 150x150px).
3. Since no resized image exists on their site with that custom 75x76px size, the image `src` is set to the original image, a large 1105 × 1113px image.

This alone isn't enough to trigger the problem in a text widget though, at least not in my tests. If I update my first image tag above to introduce the same differences as in the user's snippet:

```html
<img src="http://mysite.com/wp-content/uploads/2017/03/test-photon.jpeg" alt="" width="75" height="76" class="wp-image-1242" />
```

I still get the right image tag once it goes through Photon:

```html
<img src="https://i2.wp.com/mysite.com/wp-content/uploads/2017/03/test-photon.jpeg?resize=75%2C76" alt="" class="wp-image-1242" width="75" height="76">
```

My next step was to take the same snippet, and insert it on my test site while using a core WorPress text widget through SiteOrigin Page Builder. The results were similar to the above. Still no issues.

Last, I added an additional widget, but I used the SiteOrigin Editor from SO Widgets Bundle. I pasted the same code snippet and this time I could reproduce the issue. Here is the HTML that was outputted on the page:

```html
<img src="https://i2.wp.com/mysite.com/wp-content/uploads/2017/03/test-photon.jpeg?resize=75%2C76" alt="" class="wp-image-1242" srcset="https://i2.wp.com/mysite.com/wp-content/uploads/2017/03/test-photon.jpeg?w=600 600w, https://i2.wp.com/mysite.com/wp-content/uploads/2017/03/test-photon.jpeg?resize=300%2C200 300w, https://i2.wp.com/mysite.com/wp-content/uploads/2017/03/test-photon.jpeg?resize=162%2C108 162w" sizes="(max-width: 600px) 100vw, 600px" width="528" height="352">
```

Note the additional `srcset` parameters as well as the new `width` and `height` parameters.

The `width` and `height` parameters are added via JavaScript via [this file](https://github.com/Automattic/jetpack/blob/master/modules/photon/photon.js), but they don't have an impact here, and they were only added because they had removed beforehand. I'm not quite sure how, and where those `srcset` parameters come from, but I believe they're added by Photon via a core filter. I'm just not sure which one.

My colleague @kraftbj is more familiar with Photon and might be able to shed some light on this. @kraftbj Could you take a look?

Thanks!

**Comment by kraftbj** [comment] 2017-03-23 02:29
We took a bit of a closer look and it appears the issue is a combination of:
1. Jetpack's Photon removes the width/height html attributes to avoid having distorted images.
2. The Editor widget, seemingly after Photon has performed this change, is having it re-added.

I haven't tracked exactly where all this happens and could be wrong, but that's the direction so far.

**Comment by AlexGStapleton** [comment] 2017-03-23 15:13
@jeherve @kraftbj Thank you both so much for the comments! :)
@braamgenis is currently finishing up work on the new PB update but he'll look at this asap.

I had a look at the Jetpack commit and it looks like it's working based on widget_text and based upon @kraftbj comment, it's quite possible this has been indirectly fixed. To clarify, in the current version we run [widget_text](https://github.com/siteorigin/so-widgets-bundle/blob/1.8.1/widgets/editor/editor.php#L60) and _then_ [wp_make_content_images_responsive()](https://github.com/siteorigin/so-widgets-bundle/blob/1.8.1/widgets/editor/editor.php#L68).

In develop, we run [wp_make_content_images_responsive()](https://github.com/siteorigin/so-widgets-bundle/blob/develop/widgets/editor/editor.php#L62) and _then_ [widget_text](https://github.com/siteorigin/so-widgets-bundle/blob/develop/widgets/editor/editor.php#L72).

I'll run a few tests later on today to see if this is the case or not.

**Comment by braamgenis** [comment] 2017-03-26 13:29
@AlexGStapleton Just did a quick check and the latest from develop doesn't seem to fix things. I'll dive deeper tomorrow.

**Comment by braamgenis** [comment] 2017-03-30 10:39
@AlexGStapleton Just got back to this and it seems you were right. Switching the order of the `widget_text` filter and `wp_make_content_images_responsive()` did fix it after all. I must have tested with the wrong version of the Widgets Bundle. Just in case, are you able to test to confirm?

@jeherve @kraftbj Thanks for your detailed input. Looks like this should be fixed with the next update.

**Comment by jeherve** [comment] 2017-03-30 11:34
Great news, thanks for the update!

**Comment by AlexGStapleton** [comment] 2017-03-30 19:19
@braamgenis Just tried - it's working for me now also. 👍

**Closed** 2017-04-19 12:49 UTC
Labels: plugin/theme conflict, priority-1
