### ISSUE TITLE
Elementor not working anymore after the latest update - sideeffects with SiteOrigin Widgets Bundle

### ISSUE THREAD

**Issue by TheAgentK** [siteorigin/so-widgets-bundle#518] opened 2017-07-21 10:01 UTC
Hi, 
I am trying to use Elementor and SiteOrigin Widgets Bundle together in my project.
But after the latest Elementor update the elementor-page-editor is broken. 
I found that SiteOrigin Widgets Bundle (ver. 1.9.3) is the cause of the problem. After its deactivation, the Elementor works normally.

There is a related issue on Wordpress https://wordpress.org/support/topic/elementor-not-working-3/

**Comment by AlexGStapleton** [comment] 2017-07-21 10:28
Unfortunately, this isn't a widespread issue so we're having a really hard time replicating this issue. Once we're able to replicate it we'll definitely be able to look into what the cause is but until then we're kind of grasping at straws trying to work it out. I'm very sorry about this! :(

Just to completely confirm, does this issue happen for you if only SiteOrigin Widgets Bundle and Elementor are activated and a default theme is used?

**Comment by TheAgentK** [comment] 2017-07-21 11:35
Hey,
i know its not a widespread issue, but i think it can be usefull to hear about it.
Maybe it will be soulved with an future update of elementory...

yes, a fresh clean wordpress with default theme, elementor and SiteOrigin Widgets Bundle reproduce the error.

**Comment by AlexGStapleton** [comment] 2017-07-21 15:37
To clarify, by widespread I mean that only you and one other person have reported this issue. We would really like to resolve this issue but we need to work out how to replicate this as it's proving to be difficult. I've tried replicating this issue on a number of sites and fresh installs - not of them suffered from this issue. Hm. Can you please try replicating this issue in another browser and/or different computer?

Have you been able to replicate this issue on a different server with a different configuration (as in, either a different web host or on a local install)?

**Comment by AlexGStapleton** [comment] 2018-05-29 08:28
We haven't received any reports of this lately, and we're still unable to replicate this issue so I'm going to close this. Let me know if this issue is still occurring for you and we'll lend a hand.

**Closed by AlexGStapleton** 2018-05-29 08:28 UTC
