### ISSUE TITLE
Features Widget in Mobile View Cause Side Scroll

### ISSUE THREAD

**Issue by ibrossiter** [siteorigin/so-widgets-bundle#572] opened 2017-10-10 17:55 UTC
See the attached file. You can see how in mobile view the Features Widget container is wider than the page width resulting in side scroll.

<img width="417" alt="screen shot 2017-10-10 at 7 40 59 pm" src="https://user-images.githubusercontent.com/29685969/31401931-b141d3f8-adf4-11e7-8e95-ec2880f54844.png">

**Comment by AlexGStapleton** [comment] 2017-10-10 18:10
Duplicate of #441, I'll submit a PR in a second that will fix this.

**Closed by AlexGStapleton** 2017-10-10 18:10 UTC
Labels: bug, duplicate
