### ISSUE TITLE
Editor: Browser hangs on paste and < input (text view) if automatic paragraphs is enabled

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#184] opened 2016-04-22 16:32 UTC
If you paste a sentence into an editor widget in visual view when the automatic paragraph setting is enabled and then go to the text view and press < the browser will hang. This does not occur when the "
 Automatically add paragraphs" setting is unchecked.

It seems this doesn't happen if you paste a sentence that already contained a <.

**Comment by braamgenis** [comment] 2016-04-25 11:07
@AlexGStapleton Was this reported by someone else or just happening to you? I can't reproduce this using Chrome on Ubuntu using the following steps:

1. Open empty Editor widget with 'Automatically add paragraphs' already checked
2. Paste some text in Visual tab which is selected by default.
3. Switch to Text tab and enter '<'
4. Nothing happens. I can continue using the TinyMCE editor, switch between tabs etc.

**Comment by AlexGStapleton** [comment] 2016-04-25 16:46
Reported by someone else, and I was able to reproduce.

Hm. Not too sure what to tell you. I'm able to reproduce this very consistently.
![2016-04-26_02-44-33](https://cloud.githubusercontent.com/assets/17275120/14791390/09634e08-0b59-11e6-8c9b-134ea704e89b.gif)

**Comment by AlexGStapleton** [comment] 2016-04-25 16:47
Hm. Maybe I should have specified that you needed to input < into the text view. :sob:

**Comment by gregpriday** [comment] 2016-04-26 09:24
I've followed these steps exactly and I also can't recreate it. Adding a `<` in text view with that checkbox checked, doesn't hang things for me. Not sure what else could be causing this. What browser are you using? Maybe it's a Windows thing. I'm on a Mac and Braam is on Ubuntu.

**Comment by braamgenis** [comment] 2016-04-26 09:47
Ok, I've managed to reproduce the issue. Still not exactly sure how, but it's a start.

**Comment by AlexGStapleton** [comment] 2016-04-26 15:31
I'm able to reproduce this in Chrome. I'll get in contact with the user to ask more about the browser / OS situation. Awkwardly, as I was able to reproduce it so easily I didn't think it was necessary.

**Comment by AlexGStapleton** [comment] 2016-04-26 15:37
The user sent me a reference screenshot which looks to be Chrome on Mac.

![](https://i.imgur.com/yNxw6IJ.png)

**Comment by braamgenis** [comment] 2016-04-27 09:10
Cool, thanks. I'll still try figure this out, but perhaps we should mention to the user that switching between the editor tabs is not really recommended. See the [Word of Caution](https://make.wordpress.org/support/user-manual/content/editors/#switching-editors)™ at the bottom.

**Comment by AlexGStapleton** [comment] 2016-09-14 14:41
I can confirm that this is still an issue. I was able to replicate the issue by copying and pasting the following text:

`checked, doesn't hang things for me. Not sure what else could be causing this. What browser are you using? Maybe it's a Windows thing. I'm on a Mac and Braam is on Ubuntu.`

![](https://i.imgur.com/igVk87G.gif)

**Comment by braamgenis** [comment] 2016-11-17 09:53
**Update:** So this looks to be a bug in TinyMCE's HTML parser. Bit of an odd bug. Their RegEx times out when trying to evaluate something with an opening square bracket with the matching closing bracket. The really odd thing is, this only seems to happen when there's above a certain number combination of words and spaces. So it won't happen for shorter strings. Can see the timeout in action [here](http://regexr.com/3em8i) Also, not sure why it's not happening in the default WP TinyMCE editor. They're probably doing some processing to the string before passing it in to TinyMCE. I'll try find out what that is exactly.

**Comment by braamgenis** [comment] 2016-11-17 10:05
Ah, it does happen with the default editor. The difference is they're only passing the content to TinyMCE when switching back to the Visual editor tab and then they handle the timeout error that occurs gracefully. We pass the content along as the user types and never do anything about the timeout. I'll try replicate that behaviour in our editor.

**Comment by AlexGStapleton** [comment] 2016-11-17 12:19
Sounds good man! 👍

Should we maybe also [report it to TinyMCE](https://github.com/tinymce/tinymce/issues) so that can look into resolving the issue in the editor? I did a quick look and I can't find reference to another instance of this issue coming up.

**Comment by braamgenis** [comment] 2016-11-17 13:25
[This](https://github.com/tinymce/tinymce/issues/2186) and [this](https://github.com/tinymce/tinymce/issues/2773) sound like the same issue. Seems like the problem may be with a third party lib they're using, so it's unclear whether it will be fixed any time soon.

**Comment by AlexGStapleton** [comment] 2016-11-17 13:30
Ah. I'm blind - yeah that's definitely it.

Unlikely imo. It seems to be a long-standing issue.

**Closed** 2016-11-22 08:14 UTC
Labels: bug, priority-1
