### ISSUE TITLE
Posts Query field will only be cloned if inside of a Layout Builder

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#578] opened 2017-10-18 16:10 UTC
This issue was reported [here](https://siteorigin.com/thread/cloning-a-post-that-includes-siteorigin-post-carousel/).

The new posts query field values will only be cloned in SiteOrigin Page Builder if it was added to a widget inside of a layout builder.

**Comment by braamgenis** [comment] 2017-10-26 13:05
@AlexGStapleton I'm unable to reproduce this. Cloning a page containing a Post Carousel widget seems to work for me. Any more detail? Steps to reproduce with expected and actual behaviour?

**Comment by AlexGStapleton** [comment] 2017-10-27 02:28
Here's a video of this: https://drive.google.com/a/siteorigin.com/uc?id=0BymU-6VMHHPfOVptbFVUZUJLb0E

Here are the steps used to replicate:

1. Open or create a new page.
2. Add a post loop
3. Adjust the Post Query settings and then save.
4. Open or create a new page
5. Clone the page you just added a post loop too
6. Check Post Loop settings and you'll see that none of the post query settings have carried over.

I was able to replicate this with both the post loop and Post Carousel widget. Are you testing against the dev version or the release version?

**Comment by braamgenis** [comment] 2017-10-27 10:02
Ok, I could reproduce when using PB master, so whatever is causing this has been fixed in the develop branch of PB. I'm guessing this siteorigin/siteorigin-panels@a0ec6b78ece05086eac77c7b61509a7686f2366c

**Closed by braamgenis** 2017-10-27 10:02 UTC
Labels: bug

**Comment by AlexGStapleton** [comment] 2017-10-27 10:37
Oh neat. 👍
